### ISSUE TITLE
Health check doesn't depend on app status anymore

### ISSUE THREAD

**Issue by DerGuteMoritz** [otto-de/tesla-microservice#11]
The semantics of the health check handler were changed when they were extracted into a component with 379c809e1a6df8395827adb645b0dd23dacaaf63. Before that change the health check depended on the app status. Now it only depends on the `:locked` state and there seems to be no convenient way to  (also) make it depend on the app state again. I wonder what the rationale behind that change is and whether you would be interested in a patch to make it possible to restore the old behavior.

**Comment by stammi** [comment]
We use the health-endpoint to manage the loadbalancing of applications. If an instance reports unhealthy, it is automatically taken out of loadbalancing. Our only current use-case for that is the controlled shutdown of instances during rolling deployments.

Coupling the healthcheck to the app-status has had two negative effects:
- Status calculation of individual components of an application might become slow. E.g. it might involve looking up something in a database. Then the healthcheck will become slow, too. Timeouts will occur and eventually instances are taken out of loadbalancing mistakenly.
- A certain component might report an error because it can not fullfill its task. The error status is by default propagated to the overall application's status. If this is caused by some central infrastructure like an unavailable database, all instances are affected by this at the same time. If the healthcheck is coupled to the app-status under such circumstances, all instances of that application are taken out of loadbalancing. This results in a complete downtime. 

This is why the old behaviour should not be restored. Depending on your use-case, I see three options:
- From outside the application: Parse the json status page. Alternatively add an extra endpoint that only has the condensed overall status.
- From inside the application you can call (de.otto.tesla.stateful.health/lock-application (:health system)). It would be easy to add unlock-application if need be.
- Similar to - but independent of - the behaviour of app-status, create the oppurtunity to register a function with health that is evaluated every time the health-endpoint is called.

Patches are always welcome. Thanks!
