### ISSUE TITLE
Update CHANGES

### ISSUE THREAD

**Issue by sroidl** [otto-de/tesla-microservice#22]
Hi there,
I noticed there was no update in the CHANGES file since 0.1.24 .
What did happen since then? 
Cheers!

**Comment by stammi** [comment]
Hi,

the CHANGES.md is currently intended to cover breaking changes. AFAIK there was no breaking changes since  0.1.24. Please let us know if something breaks on your side which is not documented there.

To answer your question: 
from 0.1.24 to 0.1.33 these things were changed:
- allow nested edn-config
- obscure passwords when logging config
- add some convenience functions to the metering component

Cheers!
